### ISSUE TITLE
`momentum` on npm

### ISSUE THREAD

**Issue by PatrickJS** [ashnur/momentum#1]
do you mind giving up `momentum` on npm?

**Comment by ashnur** [comment]
I'd rather not. Can you justify that request?

**Comment by PatrickJS** [comment]
The angular team is planning on naming their new animation lib `momentum` (because Angular Momentum). The lib will be able to work in any framework other than angular hence the need for the name without a namespace. The animation lib has a killer feature of being able to control the animation at any state (his example used a slider to control the animation)

NgAnimate 2.0 preview
https://www.youtube.com/watch?v=izp5N2eeogg

**Comment by ashnur** [comment]
I understand, however I dislike puns and angular and everything angular related. So here is an idea, you suggest a similarly fitting name (with format `[a-z]+`) for my vector lib and it's obviously free to take, then I rename momentum to that. I think it's only fair for those to do the work of finding a new name who want to take my 2+ year old name :)

**Comment by PatrickJS** [comment]
what about [`momenta`](https://www.npmjs.com/package/momenta)?

**Comment by ashnur** [comment]
Seems good enough, I will probably rename it in 24-48 hours.

**Comment by PatrickJS** [comment]
thanks

**Comment by PatrickJS** [comment]
yo, any updates?

**Comment by ashnur** [comment]
Are there any problems? I see that nothing happened on the module page... Please don't tell me that I gave it to you and you are not going to use it :P

**Comment by PatrickJS** [comment]
we're going to use it don't worry :)

**Comment by ljharb** [comment]
Just be aware that if you have an empty package on `npm`, any user can request the name and be given it. Squatting is not permitted. Publish something tangible soon.
